### ISSUE TITLE
States/Provinces for Indonesia

### ISSUE THREAD

**Issue by lorenzocaum** [eventespresso/ee-packs-states-provinces#36]
@rgunawans 

We've merged your pull request. Thank you for your contribution! This will be published tomorrow morning in our wiki article here:

http://eventespresso.com/wiki/install-new-state-province-packs/

**Comment by lorenzocaum** [comment]
Now available from our documentation page for states/provinces for Event Espresso 4:

http://eventespresso.com/wiki/install-new-state-province-packs/#installation

**Comment by rgunawans** [comment]
Thanks…

 

 

 

 

Regards,

Robby Gunawan Sutanto, S.Kom, MM.
